### PR TITLE
Update to 1.9

### PR DESCRIPTION
**Pull request by HeroCC**
Fixes the Metrics error when using BlocksHub in 1.9. Example:

> [19:30:01 WARN]: org.apache.commons.lang.UnhandledException: Plugin BlocksHub v1.1 generated an exception while executing task 25
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at org.PrimeSoft.blocksHub.mcstats.MetricsLite.postPlugin(MetricsLite.java:267)
        at org.PrimeSoft.blocksHub.mcstats.MetricsLite.access$300(MetricsLite.java:49)
        at org.PrimeSoft.blocksHub.mcstats.MetricsLite$1.run(MetricsLite.java:156)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

### CODE REVIEW

**Comment by SBPrime** [comment]
All looks ok, but I don't want to move it to gradle.

**Comment by ThunderGemios10** [comment]
You said this was going to update to 1.9 but the dependency says "1.8-SNAPSHOT"

**Comment by HeroCC** [comment]
Oh yeah, oops, I meant to put that on a different branch. I'll fix it when
I get home.

**Comment by ThunderGemios10** [comment]
@HeroCC Also the package path is wrong at Metrics and MetricsLite it says org.mcstats

**Comment by HeroCC** [comment]
Huh, I thought I fixed that? Don't merge this PR for now, it seems wonky.
I'll remove Gradle and look into the package thing in a bit.

**Comment by HeroCC** [comment]
I removed the Gradle commit and put it on a different branch, this is ready to merge!

**Pull request merged**
